title: Reflection Groups Network
description: A research network on reflection groups
theme: minima

header_pages:
  - online-seminar/index.md
  - events/index.md
  - past-events/index.md
  - about-rgn/index.md
